import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  documentationSidebar: [
    'Overview',
    {
      type: 'category',
      label: 'Releases',
      link: {type: 'generated-index', title: 'Releases'},
      items: [{type: 'autogenerated', dirName: 'Releases'}],
    },
    {
      type: 'category',
      label: 'Launcher',
      link: {type: 'doc', id: 'Launcher/Overview'},
      items: [{type: 'autogenerated', dirName: 'Launcher'}],
    },
    {
      type: 'category',
      label: 'Server',
      link: {type: 'doc', id: 'Server/Overview'},
      items: [{type: 'autogenerated', dirName: 'Server'}],
    },
    {
      type: 'category',
      label: 'SDK',
      link: {type: 'doc', id: 'SDK/Overview'},
      items: [{type: 'autogenerated', dirName: 'SDK'}],
    },
    {
      type: 'category',
      label: 'Scripting',
      link: {type: 'doc', id: 'Scripting/Overview'},
      items: [{type: 'autogenerated', dirName: 'Scripting'}],
    }
  ]
};

export default sidebars;
