sources:
  - name: lancommander
    repo: LANCommander/LANCommander
    ref: main
    paths:
      - from: LANCommander.Documentation/
        to: Documentation/

  - name: bf1942
    repo: LANCommander/LANCommander.Servers.Battlefield1942
    ref: main
    paths:
      - from: Documentation/
        to: GameServers/BF1942

  # Game Servers
  - name: callofduty
    repo: LANCommander/LANCommander.Servers.CallOfDuty
    ref: main
    paths:
      - from: Documentation/
        to: GameServers/CallOfDuty

  - name: counterstrikesource
    repo: LANCommander/LANCommander.Servers.CounterStrikeSource
    ref: main
    paths:
      - from: Documentation/
        to: GameServers/CounterStrikeSource

  - name: eliteforce
    repo: LANCommander/LANCommander.Servers.EliteForce
    ref: main
    paths:
      - from: Documentation/
        to: GameServers/EliteForce

  - name: jediacademy
    repo: LANCommander/LANCommander.Servers.JediAcademy
    ref: main
    paths:
      - from: Documentation/
        to: GameServers/JediAcademy

  - name: jedioutcast
    repo: LANCommander/LANCommander.Servers.JediOutcast
    ref: main
    paths:
      - from: Documentation/
        to: GameServers/JediOutcast

  - name: quake3arena
    repo: LANCommander/LANCommander.Servers.Quake3
    ref: main
    paths:
      - from: Documentation/
        to: GameServers/Quake3Arena

  - name: rtcw
    repo: LANCommander/LANCommander.Servers.RTCW
    ref: main
    paths:
      - from: Documentation/
        to: GameServers/RTCW

  # - name: zandronum
  #   repo: LANCommander/LANCommander.Servers.Zandronum
  #   ref: main
  #   paths:
  #     - from: Documentation/
  #       to: Documentation/GameServers/Zandronum

  - name: ut2004
    repo: LANCommander/LANCommander.Servers.UT2004
    ref: main
    paths:
      - from: Documentation/
        to: GameServers/UT2004