sources:
  - name: lancommander
    repo: LANCommander/LANCommander
    ref: main
    paths:
      - from: LANCommander.Documentation/
        to: Documentation/

  # Game Servers        
  - name: counterstrikesource
    repo: LANCommander/LANCommander.Servers.CounterStrikeSource
    ref: main
    paths:
      - from: Documentation/
        to: Documentation/GameServers/CounterStrikeSource

  # - name: zandronum
  #   repo: LANCommander/LANCommander.Servers.Zandronum
  #   ref: main
  #   paths:
  #     - from: Documentation/
  #       to: Documentation/GameServers/Zandronum

  - name: ut2004
    repo: LANCommander/LANCommander.Servers.UT2004
    ref: main
    paths:
      - from: Documentation/
        to: GameServers/UT2004